// Demo/mock data used so the site works fully in the browser
// even before you connect a real backend API.
// Replace / extend this once your backend (see src/config/api.js) is ready.

export const CATEGORIES = [
  { _id: 'fiction', name: 'Fiction', slug: 'fiction' },
  { _id: 'romance', name: 'Romance', slug: 'romance' },
  { _id: 'mystery', name: 'Mystery & Thriller', slug: 'mystery' },
  { _id: 'business', name: 'Business', slug: 'business' },
  { _id: 'self-help', name: 'Self Development', slug: 'self-help' },
  { _id: 'technology', name: 'Technology', slug: 'technology' },
  { _id: 'academic', name: 'Academic', slug: 'academic' },
  { _id: 'children', name: "Children's Books", slug: 'children' },
];

const cover = (seed) => `https://picsum.photos/seed/${seed}/400/560`;

export const BOOKS = [
  { _id: "b1", title: "The Alchemist", author: "Hector Garcia", category: "Fiction", coverImage: cover("b1"), rating: 4.2, numReviews: 1426, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read fiction pick by Hector Garcia, loved by thousands of ROR readers." },
  { _id: "b2", title: "The Midnight Library", author: "Gillian Flynn", category: "Fiction", coverImage: cover("b2"), rating: 4.7, numReviews: 3071, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 250, description: "A must-read fiction pick by Gillian Flynn, loved by thousands of ROR readers." },
  { _id: "b3", title: "Norwegian Wood", author: "Paulo Coelho", category: "Fiction", coverImage: cover("b3"), rating: 4.1, numReviews: 1195, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 100, description: "A must-read fiction pick by Paulo Coelho, loved by thousands of ROR readers." },
  { _id: "b4", title: "Life of Pi", author: "Stephen Covey", category: "Fiction", coverImage: cover("b4"), rating: 4.3, numReviews: 2961, rentalPrice7Days: 59, rentalPrice14Days: 100, rentalPrice30Days: 177, securityDeposit: 150, description: "A must-read fiction pick by Stephen Covey, loved by thousands of ROR readers." },
  { _id: "b5", title: "The Kite Runner", author: "Tana French", category: "Fiction", coverImage: cover("b5"), rating: 4.6, numReviews: 326, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 250, description: "A must-read fiction pick by Tana French, loved by thousands of ROR readers." },
  { _id: "b6", title: "A Little Life", author: "Ali Hazelwood", category: "Fiction", coverImage: cover("b6"), rating: 4.3, numReviews: 1181, rentalPrice7Days: 55, rentalPrice14Days: 93, rentalPrice30Days: 165, securityDeposit: 100, description: "A must-read fiction pick by Ali Hazelwood, loved by thousands of ROR readers." },
  { _id: "b7", title: "The Book Thief", author: "Robert C. Martin", category: "Fiction", coverImage: cover("b7"), rating: 4.4, numReviews: 1770, rentalPrice7Days: 55, rentalPrice14Days: 93, rentalPrice30Days: 165, securityDeposit: 200, description: "A must-read fiction pick by Robert C. Martin, loved by thousands of ROR readers." },
  { _id: "b8", title: "Circe", author: "Daniel Kahneman", category: "Fiction", coverImage: cover("b8"), rating: 4.1, numReviews: 2181, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 250, description: "A must-read fiction pick by Daniel Kahneman, loved by thousands of ROR readers." },
  { _id: "b9", title: "The Night Circus", author: "Robert C. Martin", category: "Fiction", coverImage: cover("b9"), rating: 4.5, numReviews: 2874, rentalPrice7Days: 55, rentalPrice14Days: 93, rentalPrice30Days: 165, securityDeposit: 150, description: "A must-read fiction pick by Robert C. Martin, loved by thousands of ROR readers." },
  { _id: "b10", title: "Beach Read", author: "Kyle Simpson", category: "Fiction", coverImage: cover("b10"), rating: 4.2, numReviews: 3008, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 200, description: "A must-read fiction pick by Kyle Simpson, loved by thousands of ROR readers." },
  { _id: "b11", title: "It Ends with Us", author: "Robert C. Martin", category: "Romance", coverImage: cover("b11"), rating: 4.8, numReviews: 713, rentalPrice7Days: 59, rentalPrice14Days: 100, rentalPrice30Days: 177, securityDeposit: 200, description: "A must-read romance pick by Robert C. Martin, loved by thousands of ROR readers." },
  { _id: "b12", title: "The Hating Game", author: "Eric Ries", category: "Romance", coverImage: cover("b12"), rating: 4.6, numReviews: 1794, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 200, description: "A must-read romance pick by Eric Ries, loved by thousands of ROR readers." },
  { _id: "b13", title: "People We Meet on Vacation", author: "Casey McQuiston", category: "Romance", coverImage: cover("b13"), rating: 4.3, numReviews: 1393, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read romance pick by Casey McQuiston, loved by thousands of ROR readers." },
  { _id: "b14", title: "Beach Read 2", author: "Clayton Christensen", category: "Romance", coverImage: cover("b14"), rating: 4.7, numReviews: 969, rentalPrice7Days: 65, rentalPrice14Days: 110, rentalPrice30Days: 195, securityDeposit: 250, description: "A must-read romance pick by Clayton Christensen, loved by thousands of ROR readers." },
  { _id: "b15", title: "The Spanish Love Deception", author: "Madeline Miller", category: "Romance", coverImage: cover("b15"), rating: 4.9, numReviews: 2921, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 200, description: "A must-read romance pick by Madeline Miller, loved by thousands of ROR readers." },
  { _id: "b16", title: "Book Lovers", author: "Carl Sagan", category: "Romance", coverImage: cover("b16"), rating: 4.7, numReviews: 529, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 100, description: "A must-read romance pick by Carl Sagan, loved by thousands of ROR readers." },
  { _id: "b17", title: "Red White & Royal Blue", author: "Daniel Kahneman", category: "Romance", coverImage: cover("b17"), rating: 4.4, numReviews: 1396, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read romance pick by Daniel Kahneman, loved by thousands of ROR readers." },
  { _id: "b18", title: "The Love Hypothesis", author: "Margaret Wise Brown", category: "Romance", coverImage: cover("b18"), rating: 4.9, numReviews: 1588, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 250, description: "A must-read romance pick by Margaret Wise Brown, loved by thousands of ROR readers." },
  { _id: "b19", title: "The Silent Patient", author: "Lucy Foley", category: "Mystery & Thriller", coverImage: cover("b19"), rating: 4.8, numReviews: 2933, rentalPrice7Days: 65, rentalPrice14Days: 110, rentalPrice30Days: 195, securityDeposit: 150, description: "A must-read mystery & thriller pick by Lucy Foley, loved by thousands of ROR readers." },
  { _id: "b20", title: "Gone Girl", author: "Markus Zusak", category: "Mystery & Thriller", coverImage: cover("b20"), rating: 4.2, numReviews: 2599, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 250, description: "A must-read mystery & thriller pick by Markus Zusak, loved by thousands of ROR readers." },
  { _id: "b21", title: "The Girl on the Train", author: "Julia Donaldson", category: "Mystery & Thriller", coverImage: cover("b21"), rating: 4.6, numReviews: 1782, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read mystery & thriller pick by Julia Donaldson, loved by thousands of ROR readers." },
  { _id: "b22", title: "Verity", author: "Phil Knight", category: "Mystery & Thriller", coverImage: cover("b22"), rating: 4.5, numReviews: 492, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read mystery & thriller pick by Phil Knight, loved by thousands of ROR readers." },
  { _id: "b23", title: "The Guest List", author: "Hector Garcia", category: "Mystery & Thriller", coverImage: cover("b23"), rating: 4.2, numReviews: 3087, rentalPrice7Days: 59, rentalPrice14Days: 100, rentalPrice30Days: 177, securityDeposit: 100, description: "A must-read mystery & thriller pick by Hector Garcia, loved by thousands of ROR readers." },
  { _id: "b24", title: "The Thursday Murder Club", author: "Ruth Ware", category: "Mystery & Thriller", coverImage: cover("b24"), rating: 4.4, numReviews: 2217, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 100, description: "A must-read mystery & thriller pick by Ruth Ware, loved by thousands of ROR readers." },
  { _id: "b25", title: "Big Little Lies", author: "Gayle Laakmann McDowell", category: "Mystery & Thriller", coverImage: cover("b25"), rating: 4.7, numReviews: 3092, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 200, description: "A must-read mystery & thriller pick by Gayle Laakmann McDowell, loved by thousands of ROR readers." },
  { _id: "b26", title: "In the Woods", author: "Matt Haig", category: "Mystery & Thriller", coverImage: cover("b26"), rating: 4.3, numReviews: 947, rentalPrice7Days: 65, rentalPrice14Days: 110, rentalPrice30Days: 195, securityDeposit: 100, description: "A must-read mystery & thriller pick by Matt Haig, loved by thousands of ROR readers." },
  { _id: "b27", title: "Zero to One", author: "Gene Kim", category: "Business", coverImage: cover("b27"), rating: 4.8, numReviews: 1378, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 100, description: "A must-read business pick by Gene Kim, loved by thousands of ROR readers." },
  { _id: "b28", title: "Rich Dad Poor Dad", author: "E.B. White", category: "Business", coverImage: cover("b28"), rating: 4.6, numReviews: 2917, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read business pick by E.B. White, loved by thousands of ROR readers." },
  { _id: "b29", title: "The Lean Startup", author: "B.A. Paris", category: "Business", coverImage: cover("b29"), rating: 4.7, numReviews: 2509, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 200, description: "A must-read business pick by B.A. Paris, loved by thousands of ROR readers." },
  { _id: "b30", title: "Good to Great", author: "Ben Horowitz", category: "Business", coverImage: cover("b30"), rating: 4.1, numReviews: 1786, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 150, description: "A must-read business pick by Ben Horowitz, loved by thousands of ROR readers." },
  { _id: "b31", title: "The Hard Thing About Hard Things", author: "Colleen Hoover", category: "Business", coverImage: cover("b31"), rating: 4.3, numReviews: 2623, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 100, description: "A must-read business pick by Colleen Hoover, loved by thousands of ROR readers." },
  { _id: "b32", title: "Shoe Dog", author: "Gene Kim", category: "Business", coverImage: cover("b32"), rating: 4.5, numReviews: 583, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 150, description: "A must-read business pick by Gene Kim, loved by thousands of ROR readers." },
  { _id: "b33", title: "Principles", author: "Erich Gamma", category: "Business", coverImage: cover("b33"), rating: 4.5, numReviews: 2551, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 200, description: "A must-read business pick by Erich Gamma, loved by thousands of ROR readers." },
  { _id: "b34", title: "The Innovators Dilemma", author: "Ray Dalio", category: "Business", coverImage: cover("b34"), rating: 4.8, numReviews: 2033, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read business pick by Ray Dalio, loved by thousands of ROR readers." },
  { _id: "b35", title: "Atomic Habits", author: "Kyle Simpson", category: "Self Development", coverImage: cover("b35"), rating: 4.3, numReviews: 3051, rentalPrice7Days: 55, rentalPrice14Days: 93, rentalPrice30Days: 165, securityDeposit: 250, description: "A must-read self development pick by Kyle Simpson, loved by thousands of ROR readers." },
  { _id: "b36", title: "Deep Work", author: "Julia Donaldson", category: "Self Development", coverImage: cover("b36"), rating: 4.5, numReviews: 795, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read self development pick by Julia Donaldson, loved by thousands of ROR readers." },
  { _id: "b37", title: "The 7 Habits of Highly Effective People", author: "Peter Thiel", category: "Self Development", coverImage: cover("b37"), rating: 4.4, numReviews: 2709, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read self development pick by Peter Thiel, loved by thousands of ROR readers." },
  { _id: "b38", title: "Cant Hurt Me", author: "Alex Michaelides", category: "Self Development", coverImage: cover("b38"), rating: 4.2, numReviews: 2884, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 150, description: "A must-read self development pick by Alex Michaelides, loved by thousands of ROR readers." },
  { _id: "b39", title: "The Power of Now", author: "Peter Thiel", category: "Self Development", coverImage: cover("b39"), rating: 4.8, numReviews: 1653, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read self development pick by Peter Thiel, loved by thousands of ROR readers." },
  { _id: "b40", title: "Think Again", author: "Madeline Miller", category: "Self Development", coverImage: cover("b40"), rating: 4.6, numReviews: 1177, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 250, description: "A must-read self development pick by Madeline Miller, loved by thousands of ROR readers." },
  { _id: "b41", title: "Grit", author: "Hanya Yanagihara", category: "Self Development", coverImage: cover("b41"), rating: 4.7, numReviews: 1967, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 100, description: "A must-read self development pick by Hanya Yanagihara, loved by thousands of ROR readers." },
  { _id: "b42", title: "Ikigai", author: "Yuval Noah Harari", category: "Self Development", coverImage: cover("b42"), rating: 4.6, numReviews: 1751, rentalPrice7Days: 59, rentalPrice14Days: 100, rentalPrice30Days: 177, securityDeposit: 250, description: "A must-read self development pick by Yuval Noah Harari, loved by thousands of ROR readers." },
  { _id: "b43", title: "Clean Code", author: "Eric Ries", category: "Technology", coverImage: cover("b43"), rating: 4.8, numReviews: 521, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 100, description: "A must-read technology pick by Eric Ries, loved by thousands of ROR readers." },
  { _id: "b44", title: "The Pragmatic Programmer", author: "Lucy Foley", category: "Technology", coverImage: cover("b44"), rating: 4.7, numReviews: 747, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 150, description: "A must-read technology pick by Lucy Foley, loved by thousands of ROR readers." },
  { _id: "b45", title: "Design Patterns", author: "Haruki Murakami", category: "Technology", coverImage: cover("b45"), rating: 4.5, numReviews: 874, rentalPrice7Days: 59, rentalPrice14Days: 100, rentalPrice30Days: 177, securityDeposit: 150, description: "A must-read technology pick by Haruki Murakami, loved by thousands of ROR readers." },
  { _id: "b46", title: "Cracking the Coding Interview", author: "Madeline Miller", category: "Technology", coverImage: cover("b46"), rating: 4.5, numReviews: 608, rentalPrice7Days: 65, rentalPrice14Days: 110, rentalPrice30Days: 195, securityDeposit: 100, description: "A must-read technology pick by Madeline Miller, loved by thousands of ROR readers." },
  { _id: "b47", title: "Introduction to Algorithms", author: "Colleen Hoover", category: "Technology", coverImage: cover("b47"), rating: 4.6, numReviews: 2514, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 100, description: "A must-read technology pick by Colleen Hoover, loved by thousands of ROR readers." },
  { _id: "b48", title: "You Dont Know JS", author: "Dr. Seuss", category: "Technology", coverImage: cover("b48"), rating: 4.7, numReviews: 1268, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 250, description: "A must-read technology pick by Dr. Seuss, loved by thousands of ROR readers." },
  { _id: "b49", title: "The Phoenix Project", author: "Ben Horowitz", category: "Technology", coverImage: cover("b49"), rating: 4.5, numReviews: 1942, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 150, description: "A must-read technology pick by Ben Horowitz, loved by thousands of ROR readers." },
  { _id: "b50", title: "Refactoring", author: "Ruth Ware", category: "Technology", coverImage: cover("b50"), rating: 4.1, numReviews: 1899, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 250, description: "A must-read technology pick by Ruth Ware, loved by thousands of ROR readers." },
  { _id: "b51", title: "Sapiens", author: "Erin Morgenstern", category: "Academic", coverImage: cover("b51"), rating: 4.4, numReviews: 2576, rentalPrice7Days: 65, rentalPrice14Days: 110, rentalPrice30Days: 195, securityDeposit: 150, description: "A must-read academic pick by Erin Morgenstern, loved by thousands of ROR readers." },
  { _id: "b52", title: "Homo Deus", author: "Haruki Murakami", category: "Academic", coverImage: cover("b52"), rating: 4.3, numReviews: 539, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 200, description: "A must-read academic pick by Haruki Murakami, loved by thousands of ROR readers." },
  { _id: "b53", title: "Guns Germs and Steel", author: "Colleen Hoover", category: "Academic", coverImage: cover("b53"), rating: 4.1, numReviews: 2252, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 100, description: "A must-read academic pick by Colleen Hoover, loved by thousands of ROR readers." },
  { _id: "b54", title: "A Brief History of Time", author: "Phil Knight", category: "Academic", coverImage: cover("b54"), rating: 4.2, numReviews: 1061, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 100, description: "A must-read academic pick by Phil Knight, loved by thousands of ROR readers." },
  { _id: "b55", title: "The Selfish Gene", author: "Gayle Laakmann McDowell", category: "Academic", coverImage: cover("b55"), rating: 4.8, numReviews: 1953, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read academic pick by Gayle Laakmann McDowell, loved by thousands of ROR readers." },
  { _id: "b56", title: "Thinking Fast and Slow", author: "Eckhart Tolle", category: "Academic", coverImage: cover("b56"), rating: 4.6, numReviews: 2836, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 250, description: "A must-read academic pick by Eckhart Tolle, loved by thousands of ROR readers." },
  { _id: "b57", title: "Freakonomics", author: "Erich Gamma", category: "Academic", coverImage: cover("b57"), rating: 4.6, numReviews: 2441, rentalPrice7Days: 55, rentalPrice14Days: 93, rentalPrice30Days: 165, securityDeposit: 200, description: "A must-read academic pick by Erich Gamma, loved by thousands of ROR readers." },
  { _id: "b58", title: "Cosmos", author: "Yann Martel", category: "Academic", coverImage: cover("b58"), rating: 4.6, numReviews: 1586, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 200, description: "A must-read academic pick by Yann Martel, loved by thousands of ROR readers." },
  { _id: "b59", title: "The Very Hungry Caterpillar", author: "Lucy Foley", category: "Children's Books", coverImage: cover("b59"), rating: 4.2, numReviews: 2943, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 250, description: "A must-read children's books pick by Lucy Foley, loved by thousands of ROR readers." },
  { _id: "b60", title: "Where the Wild Things Are", author: "Sally Thorne", category: "Children's Books", coverImage: cover("b60"), rating: 4.8, numReviews: 597, rentalPrice7Days: 29, rentalPrice14Days: 49, rentalPrice30Days: 87, securityDeposit: 250, description: "A must-read children's books pick by Sally Thorne, loved by thousands of ROR readers." },
  { _id: "b61", title: "Charlottes Web", author: "Angela Duckworth", category: "Children's Books", coverImage: cover("b61"), rating: 4.9, numReviews: 709, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read children's books pick by Angela Duckworth, loved by thousands of ROR readers." },
  { _id: "b62", title: "Matilda", author: "Phil Knight", category: "Children's Books", coverImage: cover("b62"), rating: 4.3, numReviews: 1729, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read children's books pick by Phil Knight, loved by thousands of ROR readers." },
  { _id: "b63", title: "The Gruffalo", author: "B.A. Paris", category: "Children's Books", coverImage: cover("b63"), rating: 4.3, numReviews: 2094, rentalPrice7Days: 49, rentalPrice14Days: 83, rentalPrice30Days: 147, securityDeposit: 100, description: "A must-read children's books pick by B.A. Paris, loved by thousands of ROR readers." },
  { _id: "b64", title: "Goodnight Moon", author: "Erich Gamma", category: "Children's Books", coverImage: cover("b64"), rating: 4.8, numReviews: 1526, rentalPrice7Days: 35, rentalPrice14Days: 59, rentalPrice30Days: 105, securityDeposit: 150, description: "A must-read children's books pick by Erich Gamma, loved by thousands of ROR readers." },
  { _id: "b65", title: "The Cat in the Hat", author: "Markus Zusak", category: "Children's Books", coverImage: cover("b65"), rating: 4.2, numReviews: 738, rentalPrice7Days: 39, rentalPrice14Days: 66, rentalPrice30Days: 117, securityDeposit: 200, description: "A must-read children's books pick by Markus Zusak, loved by thousands of ROR readers." },
  { _id: "b66", title: "Green Eggs and Ham", author: "Erin Morgenstern", category: "Children's Books", coverImage: cover("b66"), rating: 4.6, numReviews: 1704, rentalPrice7Days: 45, rentalPrice14Days: 76, rentalPrice30Days: 135, securityDeposit: 200, description: "A must-read children's books pick by Erin Morgenstern, loved by thousands of ROR readers." },
];

export const findBooks = ({ category = 'all', search = '', sort = 'newest' } = {}) => {
  let list = [...BOOKS];
  if (category && category !== 'all') {
    list = list.filter((b) => b.category.toLowerCase() === category.toLowerCase() || b.category.toLowerCase().includes(category.toLowerCase()));
  }
  if (search) {
    const q = search.toLowerCase();
    list = list.filter((b) => b.title.toLowerCase().includes(q) || b.author.toLowerCase().includes(q));
  }
  switch (sort) {
    case 'priceLow':
      list.sort((a, b) => a.rentalPrice7Days - b.rentalPrice7Days);
      break;
    case 'priceHigh':
      list.sort((a, b) => b.rentalPrice7Days - a.rentalPrice7Days);
      break;
    case 'rating':
      list.sort((a, b) => b.rating - a.rating);
      break;
    default:
      break;
  }
  return list;
};